security:
    # Hashage des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Fournisseur d'utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Configuration des pare-feux (firewalls)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true  # Permet aux utilisateurs non authentifiés d'accéder aux pages publiques sans forcer l'authentification immédiate
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: search  # Redirige vers la page de recherche après connexion
            logout:
                path: app_logout
                target: app_login  # Redirige vers la page de connexion après déconnexion

    # Contrôle d'accès
    access_control:
        - { path: ^/login$, roles:  }
        - { path: ^/logout$, roles:  }
        - { path: ^/admin, roles:  }
        - { path: ^/profile, roles:  }
        - { path: ^/$, roles:  }  # Autorise l'accès anonyme à l'accueil
        - { path: ^/search, roles:  }  # Autorise l'accès anonyme à la recherche
        - { path: ^/, roles:  }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
