services:
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: tutti-frutti           # Nom de la base de données
      POSTGRES_USER: Max                  # Nom de l'utilisateur
      POSTGRES_PASSWORD: 123              # Mot de passe pour l'utilisateur
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "tutti-frutti", "-U", "Max"]
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw

volumes:
  database_data:
