.TH "RegistrationController" 3 "Tutti-frutti" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RegistrationController
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de AbstractController\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBindex\fP (Request $request, EntityManagerInterface $entityManager, UserPasswordHasherInterface $passwordHasher, TokenStorageInterface $tokenStorage, SessionInterface $session, SluggerInterface $slugger)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne \fB20\fP du fichier \fBRegistrationController\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "index (Request $request, EntityManagerInterface $entityManager, UserPasswordHasherInterface $passwordHasher, TokenStorageInterface $tokenStorage, SessionInterface $session, SluggerInterface $slugger)"

.PP
Définition à la ligne \fB23\fP du fichier \fBRegistrationController\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tutti-frutti à partir du code source\&.
