.TH "HomeController" 3 "Tutti-frutti" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HomeController
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de AbstractController\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBindex\fP ()"
.br
.in -1c
.SH "Description détaillée"
.PP 
Contrôleur de la page d'accueil de l'application\&. 
.PP
Définition à la ligne \fB14\fP du fichier \fBHomeController\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "index ()"
Affiche la page d'accueil\&.

.PP
@Route('/', name='app_home', methods={'GET'})

.PP
\fBRenvoie\fP
.RS 4
Response La réponse HTTP contenant le rendu de la page d'accueil\&. 
.RE
.PP

.PP
Définition à la ligne \fB24\fP du fichier \fBHomeController\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tutti-frutti à partir du code source\&.
