.TH "App\Controller" 3 "Tutti-frutti" \" -*- nroff -*-
.ad l
.nh
.SH NAME
App\Controller
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAlbumSearchController\fP"
.br
.ti -1c
.RI "class \fBConnexionController\fP"
.br
.ti -1c
.RI "class \fBDiscogsTestController\fP"
.br
.ti -1c
.RI "class \fBHomeController\fP"
.br
.ti -1c
.RI "class \fBProfileController\fP"
.br
.ti -1c
.RI "class \fBRegistrationController\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tutti-frutti à partir du code source\&.
