.TH "FormatRepository" 3 "Tutti-frutti" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FormatRepository
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de ServiceEntityRepository, et ServiceEntityRepository\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fB__construct\fP (ManagerRegistry $registry)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Repository pour l'entité Format\&.

.PP
Fournit des méthodes de base pour interagir avec la table des formats et permet d'ajouter des requêtes personnalisées si nécessaire\&.

.PP
<Format> 
.PP
Définition à la ligne \fB19\fP du fichier \fBFormatRepository\&.php\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "__construct (ManagerRegistry $registry)"
Constructeur du repository\&.

.PP
\fBParamètres\fP
.RS 4
\fI$registry\fP Le registre des gestionnaires d'entités\&. 
.RE
.PP

.PP
Définition à la ligne \fB26\fP du fichier \fBFormatRepository\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tutti-frutti à partir du code source\&.
