.TH "UpdateFavoriteCoversCommand" 3 "Tutti-frutti" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UpdateFavoriteCoversCommand
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de Command\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fB__construct\fP (EntityManagerInterface $entityManager)"
.br
.in -1c
.SS "Fonctions membres protégées"

.in +1c
.ti -1c
.RI "\fBexecute\fP (InputInterface $input, OutputInterface $output)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne \fB18\fP du fichier \fBUpdateFavoriteCoversCommand\&.php\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "__construct (EntityManagerInterface $entityManager)"
Constructeur de la commande\&.

.PP
\fBParamètres\fP
.RS 4
\fI$entityManager\fP Le gestionnaire d'entités\&. 
.RE
.PP

.PP
Définition à la ligne \fB32\fP du fichier \fBUpdateFavoriteCoversCommand\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "execute (InputInterface $input, OutputInterface $output)\fR [protected]\fP"
Exécute la commande pour mettre à jour les images par défaut des albums favoris\&.

.PP
\fBParamètres\fP
.RS 4
\fI$input\fP Interface d'entrée\&. 
.br
\fI$output\fP Interface de sortie\&.
.RE
.PP
\fBRenvoie\fP
.RS 4
int Code de statut de la commande\&. 
.RE
.PP

.PP
Définition à la ligne \fB46\fP du fichier \fBUpdateFavoriteCoversCommand\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tutti-frutti à partir du code source\&.
