.TH "App\Entity" 3 "Tutti-frutti" \" -*- nroff -*-
.ad l
.nh
.SH NAME
App\Entity
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFavoriteAlbum\fP"
.br
.ti -1c
.RI "class \fBFormat\fP"
.br
.ti -1c
.RI "class \fBFruit\fP"
.br
.ti -1c
.RI "class \fBGenre\fP"
.br
.ti -1c
.RI "class \fBLabel\fP"
.br
.ti -1c
.RI "class \fBTrack\fP"
.br
.ti -1c
.RI "class \fBUser\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tutti-frutti à partir du code source\&.
