.TH "Kernel" 3 "Tutti-frutti" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kernel
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de BaseKernel\&.
.SH "Description détaillée"
.PP 
Classe Kernel principale de l'application Symfony\&.

.PP
Elle utilise le trait \fRMicroKernelTrait\fP pour gérer une configuration simplifiée et fournit le point d'entrée principal pour l'exécution de l'application\&. 
.PP
Définition à la ligne \fB14\fP du fichier \fBKernel\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tutti-frutti à partir du code source\&.
