.TH "AlbumSearchController" 3 "Tutti-frutti" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AlbumSearchController
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de AbstractController\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBDiscogsService\fP $discogsService, EntityManagerInterface $entityManager)"
.br
.ti -1c
.RI "\fBsearch\fP (Request $request)"
.br
.ti -1c
.RI "\fBshowDetails\fP (int $id, Request $request)"
.br
.ti -1c
.RI "\fBaddToFavorites\fP (int $id)"
.br
.ti -1c
.RI "\fBremoveFromFavorites\fP (int $id)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne \fB19\fP du fichier \fBAlbumSearchController\&.php\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "__construct (\fBDiscogsService\fP $discogsService, EntityManagerInterface $entityManager)"

.PP
Définition à la ligne \fB24\fP du fichier \fBAlbumSearchController\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "addToFavorites (int $id)"

.PP
Définition à la ligne \fB89\fP du fichier \fBAlbumSearchController\&.php\fP\&.
.SS "removeFromFavorites (int $id)"

.PP
Définition à la ligne \fB117\fP du fichier \fBAlbumSearchController\&.php\fP\&.
.SS "search (Request $request)"

.PP
Définition à la ligne \fB31\fP du fichier \fBAlbumSearchController\&.php\fP\&.
.SS "showDetails (int $id, Request $request)"

.PP
Définition à la ligne \fB67\fP du fichier \fBAlbumSearchController\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tutti-frutti à partir du code source\&.
