.TH "LabelRepository" 3 "Tutti-frutti" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LabelRepository
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de ServiceEntityRepository\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fB__construct\fP (ManagerRegistry $registry)"
.br
.ti -1c
.RI "\fBfindByNamePart\fP (string $namePart)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Repository pour l'entité Label\&.

.PP
Fournit des méthodes de base pour interagir avec les labels musicaux et permet d'ajouter des méthodes personnalisées pour répondre à des besoins spécifiques\&.

.PP
@method Label|null find($id, $lockMode = null, $lockVersion = null) @method Label|null findOneBy(array $criteria, array $orderBy = null) @method Label[] findAll() @method Label[] findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null) 
.PP
Définition à la ligne \fB22\fP du fichier \fBLabelRepository\&.php\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "__construct (ManagerRegistry $registry)"
Constructeur du repository\&.

.PP
\fBParamètres\fP
.RS 4
\fI$registry\fP Le registre des gestionnaires d'entités\&. 
.RE
.PP

.PP
Définition à la ligne \fB29\fP du fichier \fBLabelRepository\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "findByNamePart (string $namePart)"
Recherche des labels par nom partiel\&.

.PP
\fBParamètres\fP
.RS 4
\fI$namePart\fP Le fragment du nom à rechercher\&. 
.RE
.PP
\fBRenvoie\fP
.RS 4
Label[] La liste des labels correspondants\&. 
.RE
.PP

.PP
Définition à la ligne \fB40\fP du fichier \fBLabelRepository\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tutti-frutti à partir du code source\&.
