.TH "App\Command" 3 "Tutti-frutti" \" -*- nroff -*-
.ad l
.nh
.SH NAME
App\Command
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTestDiscogsCommand\fP"
.br
.ti -1c
.RI "class \fBTestFavoriteAlbumsCommand\fP"
.br
.ti -1c
.RI "class \fBUpdateFavoriteCoversCommand\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "name \fB__pad0__\fP"
.br
.ti -1c
.RI "name \fBdescription\fP"
.br
.in -1c
.SH "Documentation des variables"
.PP 
.SS "name __pad0__"
Cette commande met à jour les images par défaut pour les albums favoris qui n'ont pas d'image associée\&. 
.PP
Définition à la ligne \fB15\fP du fichier \fBUpdateFavoriteCoversCommand\&.php\fP\&.
.SS "name description"

.PP
Définition à la ligne \fB16\fP du fichier \fBUpdateFavoriteCoversCommand\&.php\fP\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tutti-frutti à partir du code source\&.
