.TH "Répertoire de référence de Controller" 3 "Tutti-frutti" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de Controller
.SH SYNOPSIS
.br
.PP
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fBAlbumSearchController\&.php\fP"
.br
.ti -1c
.RI "fichier \fBConnexionController\&.php\fP"
.br
.ti -1c
.RI "fichier \fBDiscogsTestController\&.php\fP"
.br
.ti -1c
.RI "fichier \fBHomeController\&.php\fP"
.br
.ti -1c
.RI "fichier \fBProfileController\&.php\fP"
.br
.ti -1c
.RI "fichier \fBRegistrationController\&.php\fP"
.br
.in -1c
