controllers:
  resource: ../src/Controller/
  type: attribute

search_fruit:
  path: /search-fruit
  controller: App\Controller\DiscogsController::searchByFruit
  methods: [GET, POST]

album_search:
  path: /album/search
  controller: App\Controller\AlbumSearchController::search
  methods: [GET, POST]

