parameters:
    # Répertoire pour les photos de profil
    profile_pictures_directory: '%kernel.project_dir%/public/uploads/profile_pictures'

services:
    # Configuration par défaut pour tous les services
    _defaults:
        autowire: true
        autoconfigure: true

    # Configuration pour toutes les classes dans le répertoire App\
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Configuration explicite pour le service DiscogsService
    App\Service\DiscogsService:
        arguments:
            $client: '@Symfony\Contracts\HttpClient\HttpClientInterface'
            $consumerKey: '%env(DISCOGS_CONSUMER_KEY)%'
            $consumerSecret: '%env(DISCOGS_CONSUMER_SECRET)%'
