.TH "AlbumSearchType" 3 "Tutti-frutti" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AlbumSearchType
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de AbstractType\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBbuildForm\fP (FormBuilderInterface $builder, array $options)"
.br
.ti -1c
.RI "\fBconfigureOptions\fP (OptionsResolver $resolver)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Formulaire de recherche d'albums à partir de fruits\&. 
.PP
Définition à la ligne \fB16\fP du fichier \fBAlbumSearchType\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "buildForm (FormBuilderInterface $builder, array $options)"
Construit le formulaire de recherche d'albums\&.

.PP
\fBParamètres\fP
.RS 4
\fI$builder\fP Le constructeur de formulaire\&. 
.br
\fI$options\fP Les options supplémentaires pour le formulaire\&. 
.RE
.PP

.PP
Définition à la ligne \fB24\fP du fichier \fBAlbumSearchType\&.php\fP\&.
.SS "configureOptions (OptionsResolver $resolver)"
Configure les options par défaut du formulaire\&.

.PP
\fBParamètres\fP
.RS 4
\fI$resolver\fP Le résolveur d'options\&. 
.RE
.PP

.PP
Définition à la ligne \fB47\fP du fichier \fBAlbumSearchType\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tutti-frutti à partir du code source\&.
