.TH "Label" 3 "Tutti-frutti" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Label
.SH SYNOPSIS
.br
.PP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fB__construct\fP ()"
.br
.ti -1c
.RI "\fBgetId\fP ()"
.br
.ti -1c
.RI "\fBgetName\fP ()"
.br
.ti -1c
.RI "\fBsetName\fP (string $name)"
.br
.ti -1c
.RI "\fBgetFavoriteAlbums\fP ()"
.br
.ti -1c
.RI "\fBaddFavoriteAlbum\fP (\fBFavoriteAlbum\fP $favoriteAlbum)"
.br
.ti -1c
.RI "\fBremoveFavoriteAlbum\fP (\fBFavoriteAlbum\fP $favoriteAlbum)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Entité représentant un label musical associé à des albums favoris\&.

.PP
@ORM\\Entity(repositoryClass=LabelRepository::class) 
.PP
Définition à la ligne \fB16\fP du fichier \fBLabel\&.php\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "__construct ()"
Constructeur de la classe Label\&. Initialise la collection des albums favoris\&. 
.PP
Définition à la ligne \fB56\fP du fichier \fBLabel\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "addFavoriteAlbum (\fBFavoriteAlbum\fP $favoriteAlbum)"
Ajoute un album favori à la collection associée à ce label\&.

.PP
\fBParamètres\fP
.RS 4
\fI$favoriteAlbum\fP L'album favori à ajouter\&.
.RE
.PP
\fBRenvoie\fP
.RS 4
self 
.RE
.PP

.PP
Définition à la ligne \fB111\fP du fichier \fBLabel\&.php\fP\&.
.SS "getFavoriteAlbums ()"
Obtient la collection des albums favoris associés à ce label\&.

.PP
\fBRenvoie\fP
.RS 4
Collection<int, FavoriteAlbum> La collection des albums favoris\&. 
.RE
.PP

.PP
Définition à la ligne \fB99\fP du fichier \fBLabel\&.php\fP\&.
.SS "getId ()"
Obtient l'identifiant unique du label\&.

.PP
\fBRenvoie\fP
.RS 4
int|null L'identifiant du label\&. 
.RE
.PP

.PP
Définition à la ligne \fB66\fP du fichier \fBLabel\&.php\fP\&.
.SS "getName ()"
Obtient le nom du label musical\&.

.PP
\fBRenvoie\fP
.RS 4
string|null Le nom du label\&. 
.RE
.PP

.PP
Définition à la ligne \fB76\fP du fichier \fBLabel\&.php\fP\&.
.SS "removeFavoriteAlbum (\fBFavoriteAlbum\fP $favoriteAlbum)"
Retire un album favori de la collection associée à ce label\&.

.PP
\fBParamètres\fP
.RS 4
\fI$favoriteAlbum\fP L'album favori à retirer\&.
.RE
.PP
\fBRenvoie\fP
.RS 4
self 
.RE
.PP

.PP
Définition à la ligne \fB128\fP du fichier \fBLabel\&.php\fP\&.
.SS "setName (string $name)"
Définit le nom du label musical\&.

.PP
\fBParamètres\fP
.RS 4
\fI$name\fP Le nom du label\&.
.RE
.PP
\fBRenvoie\fP
.RS 4
self 
.RE
.PP

.PP
Définition à la ligne \fB88\fP du fichier \fBLabel\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tutti-frutti à partir du code source\&.
