.TH "DiscogsService" 3 "Tutti-frutti" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DiscogsService
.SH SYNOPSIS
.br
.PP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fB__construct\fP (HttpClientInterface $client, string $consumerKey, string $consumerSecret)"
.br
.ti -1c
.RI "\fBsearchAlbums\fP (string $searchTerm)"
.br
.ti -1c
.RI "\fBgetAlbumDetails\fP (int $id)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Service pour interagir avec l'API Discogs\&. Fournit des fonctionnalités pour rechercher des albums et obtenir leurs détails\&. 
.PP
Définition à la ligne \fB13\fP du fichier \fBDiscogsService\&.php\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "__construct (HttpClientInterface $client, string $consumerKey, string $consumerSecret)"
Constructeur du service Discogs\&.

.PP
\fBParamètres\fP
.RS 4
\fI$client\fP Client HTTP pour effectuer des requêtes\&. 
.br
\fI$consumerKey\fP Clé API Discogs\&. 
.br
\fI$consumerSecret\fP Secret API Discogs\&. 
.RE
.PP

.PP
Définition à la ligne \fB40\fP du fichier \fBDiscogsService\&.php\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "getAlbumDetails (int $id)"
Récupère les détails d'un album par son ID\&.

.PP
\fBParamètres\fP
.RS 4
\fI$id\fP L'identifiant de l'album\&. 
.RE
.PP
\fBRenvoie\fP
.RS 4
array Les détails de l'album\&. 
.RE
.PP

.PP
Définition à la ligne \fB75\fP du fichier \fBDiscogsService\&.php\fP\&.
.SS "searchAlbums (string $searchTerm)"
Recherche des albums correspondant à un terme\&.

.PP
\fBParamètres\fP
.RS 4
\fI$searchTerm\fP Le terme de recherche\&. 
.RE
.PP
\fBRenvoie\fP
.RS 4
array Une liste d'albums correspondant au terme\&. 
.RE
.PP

.PP
Définition à la ligne \fB53\fP du fichier \fBDiscogsService\&.php\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tutti-frutti à partir du code source\&.
