.TH "Répertoire de référence de Command" 3 "Tutti-frutti" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de Command
.SH SYNOPSIS
.br
.PP
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fBTestDiscogsCommand\&.php\fP"
.br
.ti -1c
.RI "fichier \fBTestFavoriteAlbumsCommand\&.php\fP"
.br
.ti -1c
.RI "fichier \fBUpdateFavoriteCoversCommand\&.php\fP"
.br
.in -1c
