.TH "Entity/Genre.php" 3 "Tutti-frutti" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Entity/Genre.php
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGenre\fP"
.br
.in -1c
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI "namespace \fBApp\\Entity\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tutti-frutti à partir du code source\&.
