.TH "Controller/ProfileController.php" 3 "Tutti-frutti" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Controller/ProfileController.php
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBProfileController\fP"
.br
.in -1c
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI "namespace \fBApp\\Controller\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tutti-frutti à partir du code source\&.
